version = 1

test_patterns = [
  "**/*_test.go",
  "wasmer/test/**"
]

exclude_patterns = [
  "benchmarks/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/wasmerio/go-ext-wasm"
